; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32s3]
platform=espressif32
board = rymcu-esp32-s3-devkitc-1
framework = arduino
build_flags =
  -Isrc/
  -DLV_CONF_INCLUDE_SIMPLE
  -DLV_DEMO_CONF_INCLUDE_SIMPLE
  -DLV_USE_DEMO_WIDGETS
lib_deps =
  lvgl/lvgl @ ~8.4.0
  lovyan03/LovyanGFX @ ^1.2.7
monitor_speed=115200
